/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaLara.capa7_reportes;

import SistemaLara.capa1_presentacion.util.Verificador;

/**
 *
 * @author XGamer
 */
public class FormReporteFacturaElectronica extends javax.swing.JDialog {

    /**
     * Creates new form FormReportePorLoteCliente
     */
    public FormReporteFacturaElectronica(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rSButton2 = new rojeru_san.RSButton();
        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        cboValorizacion = new rojerusan.RSComboMetro();
        btnMarca1 = new rojeru_san.RSButton();
        datefechaAdelanto = new rojeru_san.componentes.RSDateChooser();
        datefechaAdelanto1 = new rojeru_san.componentes.RSDateChooser();
        cboValorizacion1 = new rojerusan.RSComboMetro();
        cboValorizacion2 = new rojerusan.RSComboMetro();
        btnMarca2 = new rojeru_san.RSButton();
        btnMarca3 = new rojeru_san.RSButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablamarca = new rojerusan.RSTableMetro();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablamarca2 = new rojerusan.RSTableMetro();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablamarca1 = new rojerusan.RSTableMetro();
        btnMarca4 = new rojeru_san.RSButton();
        btnMarca5 = new rojeru_san.RSButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        rSPanelsSlider1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 94, 255), 2));

        jPanel2.setBackground(new java.awt.Color(255, 68, 68));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REPORTE ADALANTO POR VALORIZACIONES");

        rSButton2.setBackground(new java.awt.Color(255, 68, 68));
        rSButton2.setBorder(null);
        rSButton2.setText("X");
        rSButton2.setColorHover(new java.awt.Color(65, 94, 255));
        rSButton2.setFont(new java.awt.Font("Roboto Bold", 1, 20)); // NOI18N
        rSButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rSButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rSButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rSPanelShadow1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboValorizacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OPCIONES" }));
        cboValorizacion.setColorArrow(new java.awt.Color(65, 94, 255));
        cboValorizacion.setColorBorde(new java.awt.Color(65, 94, 255));
        cboValorizacion.setColorFondo(new java.awt.Color(65, 94, 255));
        cboValorizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cboValorizacionKeyTyped(evt);
            }
        });
        rSPanelShadow1.add(cboValorizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 150, -1));

        btnMarca1.setBackground(new java.awt.Color(0, 102, 255));
        btnMarca1.setText("DAR DE BAJA");
        btnMarca1.setColorHover(new java.awt.Color(255, 82, 54));
        btnMarca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarca1ActionPerformed(evt);
            }
        });
        rSPanelShadow1.add(btnMarca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, 120, 30));

        datefechaAdelanto.setColorBackground(new java.awt.Color(64, 95, 255));
        datefechaAdelanto.setColorButtonHover(new java.awt.Color(64, 95, 255));
        datefechaAdelanto.setColorForeground(new java.awt.Color(64, 95, 255));
        datefechaAdelanto.setFormatoFecha("dd/MM/yyyy");
        datefechaAdelanto.setFuente(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        datefechaAdelanto.setPlaceholder("FECHA HASTA ");
        datefechaAdelanto.setPreferredSize(new java.awt.Dimension(200, 40));
        rSPanelShadow1.add(datefechaAdelanto, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 160, 30));

        datefechaAdelanto1.setColorBackground(new java.awt.Color(64, 95, 255));
        datefechaAdelanto1.setColorButtonHover(new java.awt.Color(64, 95, 255));
        datefechaAdelanto1.setColorForeground(new java.awt.Color(64, 95, 255));
        datefechaAdelanto1.setFormatoFecha("dd/MM/yyyy");
        datefechaAdelanto1.setFuente(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        datefechaAdelanto1.setPlaceholder("FECHA DE");
        datefechaAdelanto1.setPreferredSize(new java.awt.Dimension(200, 40));
        rSPanelShadow1.add(datefechaAdelanto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 140, 30));

        cboValorizacion1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ESTADO" }));
        cboValorizacion1.setColorArrow(new java.awt.Color(65, 94, 255));
        cboValorizacion1.setColorBorde(new java.awt.Color(65, 94, 255));
        cboValorizacion1.setColorFondo(new java.awt.Color(65, 94, 255));
        cboValorizacion1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cboValorizacion1KeyTyped(evt);
            }
        });
        rSPanelShadow1.add(cboValorizacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, -1));

        cboValorizacion2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DOCUMENTOS" }));
        cboValorizacion2.setColorArrow(new java.awt.Color(65, 94, 255));
        cboValorizacion2.setColorBorde(new java.awt.Color(65, 94, 255));
        cboValorizacion2.setColorFondo(new java.awt.Color(65, 94, 255));
        cboValorizacion2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cboValorizacion2KeyTyped(evt);
            }
        });
        rSPanelShadow1.add(cboValorizacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 150, -1));

        btnMarca2.setBackground(new java.awt.Color(0, 102, 255));
        btnMarca2.setText("BUSCAR");
        btnMarca2.setColorHover(new java.awt.Color(255, 82, 54));
        btnMarca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarca2ActionPerformed(evt);
            }
        });
        rSPanelShadow1.add(btnMarca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 130, 30));

        btnMarca3.setBackground(new java.awt.Color(0, 102, 255));
        btnMarca3.setText("ENVIAR");
        btnMarca3.setColorHover(new java.awt.Color(255, 82, 54));
        btnMarca3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarca3ActionPerformed(evt);
            }
        });
        rSPanelShadow1.add(btnMarca3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 100, 30));

        tablamarca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablamarca.setAltoHead(25);
        tablamarca.setColorBackgoundHead(new java.awt.Color(255, 218, 31));
        tablamarca.setColorFilasForeground1(new java.awt.Color(65, 94, 255));
        tablamarca.setColorFilasForeground2(new java.awt.Color(65, 94, 255));
        tablamarca.setColorSelBackgound(new java.awt.Color(253, 173, 1));
        tablamarca.setFuenteHead(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tablamarca.setGrosorBordeFilas(0);
        tablamarca.setGrosorBordeHead(0);
        tablamarca.setRowHeight(25);
        tablamarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablamarcaMousePressed(evt);
            }
        });
        tablamarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablamarcaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tablamarcaKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(tablamarca);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(65, 94, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ESTADO DE FACTURA EXITOSA");

        tablamarca2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUMERO FACTURA", "ESTADO FACTURA"
            }
        ));
        tablamarca2.setAltoHead(25);
        tablamarca2.setColorBackgoundHead(new java.awt.Color(255, 218, 31));
        tablamarca2.setColorFilasForeground1(new java.awt.Color(65, 94, 255));
        tablamarca2.setColorFilasForeground2(new java.awt.Color(65, 94, 255));
        tablamarca2.setColorSelBackgound(new java.awt.Color(253, 173, 1));
        tablamarca2.setFuenteHead(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tablamarca2.setGrosorBordeFilas(0);
        tablamarca2.setGrosorBordeHead(0);
        tablamarca2.setRowHeight(25);
        tablamarca2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablamarca2MousePressed(evt);
            }
        });
        tablamarca2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablamarca2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tablamarca2KeyTyped(evt);
            }
        });
        jScrollPane5.setViewportView(tablamarca2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(65, 94, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ESTADO DE FACTURA ERRORES");

        tablamarca1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUMERO FACTURA", "ESTADO FACTURA"
            }
        ));
        tablamarca1.setAltoHead(25);
        tablamarca1.setColorBackgoundHead(new java.awt.Color(255, 218, 31));
        tablamarca1.setColorFilasForeground1(new java.awt.Color(65, 94, 255));
        tablamarca1.setColorFilasForeground2(new java.awt.Color(65, 94, 255));
        tablamarca1.setColorSelBackgound(new java.awt.Color(253, 173, 1));
        tablamarca1.setFuenteHead(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tablamarca1.setGrosorBordeFilas(0);
        tablamarca1.setGrosorBordeHead(0);
        tablamarca1.setRowHeight(25);
        tablamarca1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablamarca1MousePressed(evt);
            }
        });
        tablamarca1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablamarca1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tablamarca1KeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(tablamarca1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnMarca4.setBackground(new java.awt.Color(0, 102, 255));
        btnMarca4.setText("GENERAR PDF");
        btnMarca4.setColorHover(new java.awt.Color(255, 82, 54));
        btnMarca4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarca4ActionPerformed(evt);
            }
        });

        btnMarca5.setBackground(new java.awt.Color(0, 102, 255));
        btnMarca5.setText("VER");
        btnMarca5.setColorHover(new java.awt.Color(255, 82, 54));
        btnMarca5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarca5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, 1305, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btnMarca4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMarca5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSPanelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnMarca4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMarca5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        rSPanelsSlider1.add(jPanel1, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelsSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelsSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_rSButton2ActionPerformed

    private void cboValorizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboValorizacionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cboValorizacionKeyTyped

    private void tablamarcaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablamarcaMousePressed

    }//GEN-LAST:event_tablamarcaMousePressed

    private void tablamarcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablamarcaKeyReleased

    }//GEN-LAST:event_tablamarcaKeyReleased

    private void tablamarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablamarcaKeyTyped

    }//GEN-LAST:event_tablamarcaKeyTyped

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        Verificador.MousePressed(evt);
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
       Verificador.MouseDragged(evt, this);
    }//GEN-LAST:event_formMouseDragged

    private void btnMarca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarca1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMarca1ActionPerformed

    private void cboValorizacion1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboValorizacion1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cboValorizacion1KeyTyped

    private void cboValorizacion2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboValorizacion2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cboValorizacion2KeyTyped

    private void btnMarca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarca2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMarca2ActionPerformed

    private void btnMarca3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarca3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMarca3ActionPerformed

    private void tablamarca1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablamarca1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tablamarca1MousePressed

    private void tablamarca1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablamarca1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tablamarca1KeyReleased

    private void tablamarca1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablamarca1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tablamarca1KeyTyped

    private void tablamarca2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablamarca2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tablamarca2MousePressed

    private void tablamarca2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablamarca2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tablamarca2KeyReleased

    private void tablamarca2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablamarca2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tablamarca2KeyTyped

    private void btnMarca4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarca4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMarca4ActionPerformed

    private void btnMarca5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarca5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMarca5ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormReportePorLoteCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormReportePorLoteCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormReportePorLoteCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormReportePorLoteCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FormReportePorLoteCliente dialog = new FormReportePorLoteCliente(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnMarca1;
    private rojeru_san.RSButton btnMarca2;
    private rojeru_san.RSButton btnMarca3;
    private rojeru_san.RSButton btnMarca4;
    private rojeru_san.RSButton btnMarca5;
    private rojerusan.RSComboMetro cboValorizacion;
    private rojerusan.RSComboMetro cboValorizacion1;
    private rojerusan.RSComboMetro cboValorizacion2;
    private rojeru_san.componentes.RSDateChooser datefechaAdelanto;
    private rojeru_san.componentes.RSDateChooser datefechaAdelanto1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private rojeru_san.RSButton rSButton2;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    private rojerusan.RSTableMetro tablamarca;
    private rojerusan.RSTableMetro tablamarca1;
    private rojerusan.RSTableMetro tablamarca2;
    // End of variables declaration//GEN-END:variables
}
