/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaLara.capa7_reportes;

import SistemaLara.capa1_presentacion.util.Verificador;

/**
 *
 * @author XGamer
 */
public class FormReportePorValorizaciones extends javax.swing.JDialog {

    /**
     * Creates new form FormReportePorLoteCliente
     */
    public FormReportePorValorizaciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rSButton2 = new rojeru_san.RSButton();
        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        cboValorizacion = new rojerusan.RSComboMetro();
        btnMarca = new rojeru_san.RSButton();
        btnMarca1 = new rojeru_san.RSButton();
        rSYearDate1 = new rojerusan.RSYearDate();
        jXSearchField1 = new org.jdesktop.swingx.JXSearchField();
        datefechaAdelanto = new rojeru_san.componentes.RSDateChooser();
        datefechaAdelanto1 = new rojeru_san.componentes.RSDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablamarca = new rojerusan.RSTableMetro();
        rSPanelShadow2 = new rojeru_san.RSPanelShadow();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        rSPanelsSlider1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 94, 255), 2));

        jPanel2.setBackground(new java.awt.Color(255, 68, 68));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REPORTE ADALANTO POR VALORIZACIONES");

        rSButton2.setBackground(new java.awt.Color(255, 68, 68));
        rSButton2.setBorder(null);
        rSButton2.setText("X");
        rSButton2.setColorHover(new java.awt.Color(65, 94, 255));
        rSButton2.setFont(new java.awt.Font("Roboto Bold", 1, 20)); // NOI18N
        rSButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rSButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rSButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rSPanelShadow1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboValorizacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MOSTRAR TODOS", " " }));
        cboValorizacion.setColorArrow(new java.awt.Color(65, 94, 255));
        cboValorizacion.setColorBorde(new java.awt.Color(65, 94, 255));
        cboValorizacion.setColorFondo(new java.awt.Color(65, 94, 255));
        cboValorizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cboValorizacionKeyTyped(evt);
            }
        });
        rSPanelShadow1.add(cboValorizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        btnMarca.setBackground(new java.awt.Color(0, 102, 255));
        btnMarca.setText("IMPRIMIR");
        btnMarca.setColorHover(new java.awt.Color(255, 82, 54));
        btnMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcaActionPerformed(evt);
            }
        });
        rSPanelShadow1.add(btnMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 100, 30));

        btnMarca1.setBackground(new java.awt.Color(0, 102, 255));
        btnMarca1.setText("EXPORTAR  EXCEL");
        btnMarca1.setColorHover(new java.awt.Color(255, 82, 54));
        btnMarca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarca1ActionPerformed(evt);
            }
        });
        rSPanelShadow1.add(btnMarca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 160, 30));

        rSYearDate1.setColorBackground(new java.awt.Color(65, 94, 255));
        rSYearDate1.setColorButtonHover(new java.awt.Color(244, 67, 54));
        rSPanelShadow1.add(rSYearDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, 30));

        jXSearchField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(65, 94, 255)));
        jXSearchField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jXSearchField1.setToolTipText("BUSCAR");
        rSPanelShadow1.add(jXSearchField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 12, 240, 30));

        datefechaAdelanto.setColorBackground(new java.awt.Color(64, 95, 255));
        datefechaAdelanto.setColorButtonHover(new java.awt.Color(64, 95, 255));
        datefechaAdelanto.setColorForeground(new java.awt.Color(64, 95, 255));
        datefechaAdelanto.setFormatoFecha("dd/MM/yyyy");
        datefechaAdelanto.setFuente(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        datefechaAdelanto.setPlaceholder("FECHA HASTA ");
        datefechaAdelanto.setPreferredSize(new java.awt.Dimension(200, 40));
        rSPanelShadow1.add(datefechaAdelanto, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 130, 30));

        datefechaAdelanto1.setColorBackground(new java.awt.Color(64, 95, 255));
        datefechaAdelanto1.setColorButtonHover(new java.awt.Color(64, 95, 255));
        datefechaAdelanto1.setColorForeground(new java.awt.Color(64, 95, 255));
        datefechaAdelanto1.setFormatoFecha("dd/MM/yyyy");
        datefechaAdelanto1.setFuente(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        datefechaAdelanto1.setPlaceholder("FECHA DE");
        datefechaAdelanto1.setPreferredSize(new java.awt.Dimension(200, 40));
        rSPanelShadow1.add(datefechaAdelanto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 130, 30));

        tablamarca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablamarca.setAltoHead(30);
        tablamarca.setColorBackgoundHead(new java.awt.Color(255, 218, 31));
        tablamarca.setColorFilasForeground1(new java.awt.Color(65, 94, 255));
        tablamarca.setColorFilasForeground2(new java.awt.Color(65, 94, 255));
        tablamarca.setColorSelBackgound(new java.awt.Color(253, 173, 1));
        tablamarca.setGrosorBordeFilas(0);
        tablamarca.setGrosorBordeHead(0);
        tablamarca.setRowHeight(25);
        tablamarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablamarcaMousePressed(evt);
            }
        });
        tablamarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablamarcaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tablamarcaKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(tablamarca);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Total Porcentaje :");

        javax.swing.GroupLayout rSPanelShadow2Layout = new javax.swing.GroupLayout(rSPanelShadow2);
        rSPanelShadow2.setLayout(rSPanelShadow2Layout);
        rSPanelShadow2Layout.setHorizontalGroup(
            rSPanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelShadow2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        rSPanelShadow2Layout.setVerticalGroup(
            rSPanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelShadow2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, 1305, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(rSPanelShadow2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSPanelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(rSPanelShadow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        rSPanelsSlider1.add(jPanel1, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelsSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelsSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_rSButton2ActionPerformed

    private void cboValorizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboValorizacionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cboValorizacionKeyTyped

    private void tablamarcaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablamarcaMousePressed

    }//GEN-LAST:event_tablamarcaMousePressed

    private void tablamarcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablamarcaKeyReleased

    }//GEN-LAST:event_tablamarcaKeyReleased

    private void tablamarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablamarcaKeyTyped

    }//GEN-LAST:event_tablamarcaKeyTyped

    private void btnMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcaActionPerformed
     
    }//GEN-LAST:event_btnMarcaActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        Verificador.MousePressed(evt);
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
       Verificador.MouseDragged(evt, this);
    }//GEN-LAST:event_formMouseDragged

    private void btnMarca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarca1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMarca1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormReportePorLoteCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormReportePorLoteCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormReportePorLoteCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormReportePorLoteCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FormReportePorLoteCliente dialog = new FormReportePorLoteCliente(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnMarca;
    private rojeru_san.RSButton btnMarca1;
    private rojerusan.RSComboMetro cboValorizacion;
    private rojeru_san.componentes.RSDateChooser datefechaAdelanto;
    private rojeru_san.componentes.RSDateChooser datefechaAdelanto1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private org.jdesktop.swingx.JXSearchField jXSearchField1;
    private rojeru_san.RSButton rSButton2;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private rojeru_san.RSPanelShadow rSPanelShadow2;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    private rojerusan.RSYearDate rSYearDate1;
    private rojerusan.RSTableMetro tablamarca;
    // End of variables declaration//GEN-END:variables
}
